[package]
name = "rustmfd"
version = "0.1.0"
authors = ["Thomas Antony <mail@thomasantony.com"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false

[dependencies]
cxx = "0.3"


[build-dependencies]
cxx-build = "0.3"